# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
#title: Sculpin Blog Skeleton
#subtitle: To Get You Started

# Insert your disqus shortname
#disqus:
#    shortname:

talks:
  de:
    - id: 7
      title: "Fun about recruiting"
      subtitle: "Let's turn the tables"
      link: /de/vortraege/fun-about-recruiting.html
      active_nav: fun-about-recruiting
      image:
        url: /assets/img/fun-about-recruiting/true-tech-talks-001.jpg
        alt: "Erste Folie aus Sebastian Thoss'p Presentation zu fun about recruiting"
      tags:
        - soft-skills

    - id: 6
      title: "Git"
      subtitle: "basics"
      link: /de/vortraege/git-basics.html
      active_nav: git-basics
      image:
        url: /assets/img/git-basics/bs-14-slides-001.jpg
        alt: "Erste Folie aus Sebastian Thoss's Vortrag &uuml;ber Git - basics"
      tags:
        - git

    - id: 5
      title: "Git"
      subtitle: "Workflows and best practices"
      link: /de/vortraege/git-workflows-and-best-practices.html
      active_nav: git-workflows
      image:
        url: /assets/img/git-workflows-and-best-practices/bs-14-slides-001.jpg
        alt: "Erste Folie aus Sebastian Thoss's Vortrag &uuml;ber Git - Workflows and best practices"
      tags:
        - git

    - id: 3
      title: "SmokeTests"
      subtitle: "Let's try to burn down servers"
      link: /de/vortraege/smoke-tests.html
      active_nav: talks-smoke-tests
      image:
        url: /assets/img/smoke-tests/kam-slides-001.jpg
        alt: "Erste Folie aus Sebastian Thoss's Vortrag &uuml; SmokeTests- Why you should try to burn down your production environment"
      tags:
        - testing

    - id: 2
      title: "99%"
      subtitle: "is not enough"
      link: /de/vortraege/99-percent-is-not-enough.html
      active_nav: talks-99
      image:
        url: /assets/img/99-percent-is-not-enough/phpughh-slides-1-small.jpg
        alt: "Erste Folie aus Sebastian Thoss's Vortrag &uuml;ber Testing von Software"
      tags:
        - architecture
        - testing

    - id: 1
      title: "Don't fear the walking dead"
      subtitle: how to get rid of a zombie
      link: /de/vortraege/don-t-fear-the-walking-dead.html
      active_nav: talks-fury
      image:
        url: /assets/img/don-t-fear-the-walking-dead/ipc-1.png
        alt: "Erste Folie aus Sebastian Thoss's Vortrag, wie man mit Zombie Software umgeht"
      tags:
        - architecture

  en:
    - id: 8
      title: "How to build a startup"
      subtitle: "digital and alone"
      link: /en/talks/how-to-build-a-startup-digital-and-alone.html
      active_nav: startup
      image:
        url: /assets/img/how-to-build-a-startup-digtal-and-alone/itech-bs-14-business-school-001.jpg
        alt: First slide of Sebastian Thoss talk How to build a startup - digital and alone
      tags:
        - architecture
        - soft-skills

    - id: 7
      title: "Fun about recruiting"
      subtitle: "Let's turn the tables"
      link: /en/talks/fun-about-recruiting.html
      active_nav: fun-about-recruiting
      image:
        url: /assets/img/fun-about-recruiting/true-tech-talks-001.jpg
        alt: First slide of Sebastian Thoss presentation fun about recruiting
      tags:
        - soft-skills

    - id: 6
      title: "Git"
      subtitle: "basics"
      link: /en/talks/git-basics.html
      active_nav: git-basics
      image:
        url: /assets/img/git-basics/bs-14-slides-001.jpg
        alt: First slide of Sebastian Thoss presentation git basics
      tags:
        - git

    - id: 5
      title: "Git"
      subtitle: "Workflows and best practices"
      link: /en/talks/git-workflows-and-best-practices.html
      active_nav: git-workflows
      image:
        url: /assets/img/git-workflows-and-best-practices/bs-14-slides-001.jpg
        alt: First slide of Sebastian Thoss presentation git Workflows and best practices
      tags:
        - git

    - id: 3
      title: "SmokeTests"
      subtitle: "Let's try to burn down servers"
      link: /en/talks/smoke-tests.html
      active_nav: talks-smoke-tests
      image:
        url: /assets/img/smoke-tests/kam-slides-001.jpg
        alt: This talk is currently under construction
      tags:
        - testing

    - id: 2
      title: "99%"
      subtitle: "is not enough"
      link: /en/talks/99-percent-is-not-enough.html
      active_nav: talks-99
      image:
        url: /assets/img/99-percent-is-not-enough/phpughh-slides-1-small.jpg
        alt: First slide of Sebastian Thoss presentation 99 percent is not enough
      tags:
        - architecture
        - testing

    - id: 1
      title: "Don't fear the walking dead"
      subtitle: how to get rid of a zombie
      link: /en/talks/don-t-fear-the-walking-dead.html
      active_nav: talks-fury
      image:
        url: /assets/img/don-t-fear-the-walking-dead/ipc-1.png
        alt: First slide of Sebastian Thoss presentation do not fear the walking dead
      tags:
        - architecture
